language: generic
services:
  - docker

before_install: 
  - sudo docker build -t adelgado95/docker-react -f Dockerfile.dev .

script:
  - sudo docker run -e CI=true adelgado95/docker-react npm run test