language: generic
services:
  - docker

before_install: 
  - docker build -t adelgado95/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adelgado95/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker2"
  env: "Docker2-env"
  bucket_name: "elasticbeanstalk-us-west-1-465756757559"
  bucket_path: "docker2"
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_KEY